Feauture/profile api implementation
femmecubator/femmecubator-ui-repo pull request #151
Opened 2021-09-24 13:09 UTC by dev-catalyst

### Ticket
closes #

### Checklist
- [ ] There are no warnings in the browser console
- [ ] I made sure the component is WCAG compliant using ANDI
- [ ] I made sure the UI follows the style guide in the wireframe (font, font-size, etc...)
- [ ] I made sure that the screen reader can read all the text
- [ ] I made sure I removed all the console.logs
- [ ] I made sure mobile portrait view looks good
- [ ] I made sure mobile landscape view looks good
- [ ] I added storybook for the component
	- [ ] Storybook not applicable
- [ ] I added unit test coverage
	- [ ] I added integration test coverage
	- [ ] Unit test coverage not applicable

### To Do
- [ ] 

### Additional Notes

2021-09-27 03:00 UTC, cfernando415 requested changes
pls see comment

2021-09-27 12:44 UTC, dev-catalyst commented
All concerns are resolved.

2021-09-28 15:00 UTC, cfernando415 commented on src/components/Directory/BookDialog/index.js
> +  // };
resolved in commit # https://github.com/femmecubator/femmecubator-ui-repo/pull/151/commits/d792130f319cae1337b7751551c15b60ae41b756

2021-09-28 15:01 UTC, cfernando415 commented on src/components/Directory/BookDialog/index.js
> +  // Awesome dialog handlers
resolved in commit # https://github.com/femmecubator/femmecubator-ui-repo/pull/151/commits/d792130f319cae1337b7751551c15b60ae41b756

2021-09-28 15:01 UTC, cfernando415 commented on src/components/Directory/BookDialog/index.js
> +  // Confirm Dialog handlers
resolved in commit # https://github.com/femmecubator/femmecubator-ui-repo/pull/151/commits/d792130f319cae1337b7751551c15b60ae41b756

2021-09-28 15:01 UTC, cfernando415 commented on src/components/ViewContainer/index.js
> +      console.log(err);
resolved in commit # https://github.com/femmecubator/femmecubator-ui-repo/pull/151/commits/fc70b4325b3d392792a9473fcbb706fc2c76b428

2021-09-28 15:01 UTC, cfernando415 commented on src/components/Settings/TimeSlotModal/index.js
> +  };
resolved in commit # https://github.com/femmecubator/femmecubator-ui-repo/pull/151/commits/fc70b4325b3d392792a9473fcbb706fc2c76b428

2021-09-28 15:02 UTC, cfernando415 commented on src/components/Settings/AccountInfo.js
> +              // onChange={e => setEmail(e.target.value)}
resolve in commit # https://github.com/femmecubator/femmecubator-ui-repo/pull/151/commits/d792130f319cae1337b7751551c15b60ae41b756

2021-09-28 15:02 UTC, cfernando415 commented on package.json
> +    "moment": "^2.29.1",
resolved in commit # https://github.com/femmecubator/femmecubator-ui-repo/pull/151/commits/0270f9d01db7048b1dea9c29f581144c7b52baeb

2021-09-28 15:03 UTC, cfernando415 approved these changes
:+1:

2021-09-28 15:03 UTC, merged