Feature/session timeout
femmecubator/femmecubator-ui-repo pull request #98
Opened 2021-01-11 19:26 UTC by erocknine

https://trello.com/c/3MDz7gnh/32-session-timeout

## Tickets
### Timeout Component
- Added Timeout component in /components/Timeout. Timeout component wraps entire application in App.js.
- Timeout component uses .env file with variables `REACT_APP_IDLETIME` and `REACT_APP_COUNTDOWNTIME` representing time in milliseconds.
- `idleTime` determines the duration of time a user is idle before launching countdown modal. `countdownTime` determines the duration before the user is automatically logged off, duration displayed on UI modal to user.

### Countdown Modal Component
- Added countdown timer modal containing log off and continue buttons. Countdown time is shown to users.
- Changed previous CSS to css-in-js using Material.

## To Dos
- Possibly use JS Date() to check idle time for more accuracy.
- Write unit tests and storybook.

## Screenshot
![Screenshot_2021-01-11 Femmecubator](https://user-images.githubusercontent.com/43048422/104227766-e2bdc280-5417-11eb-8b5f-61fc9c715163.png)
![Screenshot_2021-01-11 Femmecubator(2)](https://user-images.githubusercontent.com/43048422/104227772-e4878600-5417-11eb-99c4-0b3736a19203.png)

2021-01-13 23:23 UTC, cfernando415 requested changes
please see comments

2021-01-13 23:23 UTC, cfernando415 commented on src/components/Timeout/Timeout.js
> +export default function Timeout(props) {
lets destructure the props:

`export default function Timeout({ children }) {...`

2021-01-13 23:23 UTC, cfernando415 commented on src/components/Timeout/Timeout.js
> +    </div>
refactor, if you have more than 2 or more attribs use es6 syntax:

`<div onMouseOver={reset} onKeyPress={reset}>
      {idle && (
        <Modal
          {...{countdownTime: countdownTime,
          setIdle: setIdle,
          logoff: logoff,
          timedOut: timedOut}}
        />)}{children}</div>`

2021-01-13 23:23 UTC, cfernando415 commented on src/components/Timeout/Timeout.js
> +                onClick={() => logoff()}
`onClick={logoff}`

2021-05-06 00:08 UTC, cfernando415 requested changes
pls see comments

2021-05-06 00:08 UTC, cfernando415 commented on src/components/Timeout/ModalPopup.js
> +                tabIndex="0"
let's rewrite using es6
`{...{className: classes.modal__center_div__buttons__button_logoff,
                onClick: logoff,
                onKeyPress: logoff,
                'aria-label': 'log off'
                tabIndex: '0'}}`

2021-05-06 00:08 UTC, cfernando415 commented on src/components/Timeout/ModalPopup.js
> +                tabIndex="0"
same here

2021-05-06 17:50 UTC, sherouk commented on package.json
> +    "singleQuote": true
good question...not sure. will look into it

2021-05-06 20:59 UTC, sherouk commented
@cfernando415 requested changes complete

2021-05-06 22:54 UTC, cfernando415 approved these changes
:+1:

2021-05-06 22:54 UTC, merged